baseURL = "https://www.lixueduan.com"
languageCode = "zh-CN"
title = "幻境云图"
theme = "maupassant"
googleAnalytics = "UA-131397277-1"  # UA-XXXXXXXX-X

## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140


[author]
  name = "意琦行"

[params]
  author = "意琦行"
  subtitle = "勿在浮沙筑高台"
  keywords = "golang,go语言,go语言笔记,幻境云图,java,博客"
  description = "幻境云图是一个专注于后端技术分享的博客,记录了一个菜鸟从0开始的进阶之路。主要涉及服务端相关知识共享、实践教程、前沿技术共同学习等。包括但不限于数据库,源码分析,分布式,微服务,并发编程,Docker,Kubernetes,Java,Golang等"
  busuanzi = true #启用不算子网页统计
  googleAd = "ca-pub-7693630257897132"  #谷歌广告ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = true  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "VAPTCHA"
  name = "智能手势验证码"
  url = "https://www.vaptcha.com/"


## 侧边栏广告位
#[[params.ads]]
 # title = "【2019双12】ALL IN CLoud 低至1折"
 # url = "https://www.aliyun.com/minisite/goods?userCode=jdg9oj97&share_source=copy_link"
 # img = "https://img.alicdn.com/tfs/TB1_rYHo7P2gK0jSZPxXXacQpXa-690-388.jpg"

#disqusShortname = "yourdiscussshortname"  ## 是否开启disqus评论，不要和utteranc同时开启
## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "illusorycloud/blog-comments" # 存储评论的Repo，格式为 owner/repo
  issueTerm = "pathname" #表示你选择以那种方式让github issue的评论和你的文章关联。 `pathname` 以路径的方式，推荐选项，这样你换域名的时候就不用担心评论找不到了(推荐) `url` 全链接URL路径的方式。 `title` 按页面title标题的方式。
  theme = "github-light"  # 样式主题，有github-light和github-dark两种

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = true
    style = "github"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
